# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCusto',
            fields=[
                ('id_controlecusto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data')),
                ('valor_ganho_renda', models.IntegerField(blank=True, null=True, verbose_name='Valor Ganho')),
                ('valor_anterior_despesa', models.IntegerField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_retirado_despesa', models.IntegerField(blank=True, null=True, verbose_name='Valor Retirado')),
                ('valor_atual_despesa', models.IntegerField(blank=True, null=True, verbose_name='Valor Atual')),
                ('comentario', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentário')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id_despesa', models.AutoField(primary_key=True, serialize=False)),
                ('tipodespesa', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id_divida', models.AutoField(primary_key=True, serialize=False)),
                ('nome_divida', models.CharField(max_length=45, verbose_name='Nome da Divida')),
                ('data_inicio', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Inicio')),
                ('data_atual', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Atual')),
                ('data_fim', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Fim')),
                ('valor_parcela', models.IntegerField(blank=True, null=True, verbose_name='Valor Parcela')),
                ('valor_divida', models.IntegerField(blank=True, null=True, verbose_name='Valor Divida')),
                ('valor_pago', models.IntegerField(blank=True, null=True, verbose_name='Valor Pago')),
            ],
        ),
        migrations.CreateModel(
            name='ItensDesejados',
            fields=[
                ('id_itemdesejado', models.AutoField(primary_key=True, serialize=False)),
                ('data_prevista', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data Prevista de Compra')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome do Item')),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='default/users')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor do Item')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id_parcela', models.AutoField(primary_key=True, serialize=False)),
                ('parcela', models.CharField(blank=True, max_length=45, null=True, verbose_name='Parcelas')),
            ],
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id_renda', models.AutoField(primary_key=True, serialize=False)),
                ('tiporenda', models.CharField(max_length=45, verbose_name='Tipo de Renda')),
            ],
        ),
        migrations.CreateModel(
            name='Seguranca',
            fields=[
                ('id_seguranca', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45, verbose_name='E-mail')),
                ('senha', models.CharField(blank=True, max_length=45, null=True, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id_tipoconta', models.AutoField(primary_key=True, serialize=False)),
                ('tipoconta', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de Conta')),
            ],
        ),
        migrations.AddField(
            model_name='seguranca',
            name='id_tipoconta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.TipoConta', verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='divida',
            name='id_parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parcela', verbose_name='Parcelas do Produto'),
        ),
        migrations.AddField(
            model_name='controlecusto',
            name='id_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Despesa', verbose_name='Tipo de Despesa'),
        ),
        migrations.AddField(
            model_name='controlecusto',
            name='id_renda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Renda', verbose_name='Tipo de Renda'),
        ),
    ]
